-- ============================================================
-- IBPS Management Console - Database Schema
-- OceanBase Oracle Mode Compatible DDL
-- ============================================================

-- 1. Connection Status
CREATE TABLE TB_IBPS_CONNECTION_STATUS (
    ID              NUMBER(20) PRIMARY KEY,
    INST_CODE       VARCHAR2(20) NOT NULL,
    STATUS          VARCHAR2(10) NOT NULL,
    SIGN_TIME       TIMESTAMP(3),
    SIGN_OUT_TIME   TIMESTAMP(3),
    OPERATOR        VARCHAR2(64),
    REMARK          VARCHAR2(500),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE,
    UPDATE_TIME     TIMESTAMP(3)
);

COMMENT ON TABLE TB_IBPS_CONNECTION_STATUS IS '联机状态表';
COMMENT ON COLUMN TB_IBPS_CONNECTION_STATUS.STATUS IS 'SIGNED_IN-已签到, SIGNED_OUT-已签退, ABNORMAL-异常';

-- 2. Free Format Messages
CREATE TABLE TB_IBPS_FREE_MESSAGE (
    ID                      NUMBER(20) PRIMARY KEY,
    BUSI_SERIAL             VARCHAR2(64),
    MSG_DIRECTION           VARCHAR2(10) NOT NULL,
    SENDER_CODE             VARCHAR2(20),
    RECEIVER_CODE           VARCHAR2(20),
    MSG_CONTENT             CLOB NOT NULL,
    PRIORITY                NUMBER(2) DEFAULT 5,
    SEND_STATUS             VARCHAR2(20),
    MSG_REF                 VARCHAR2(50),
    CROSS_BORDER_TYPE       VARCHAR2(20),
    CROSS_BORDER_ORIG_SERIAL VARCHAR2(64),
    CREATE_TIME             TIMESTAMP(3) DEFAULT SYSDATE,
    UPDATE_TIME             TIMESTAMP(3)
);

COMMENT ON TABLE TB_IBPS_FREE_MESSAGE IS '自由格式报文表';
COMMENT ON COLUMN TB_IBPS_FREE_MESSAGE.BUSI_SERIAL IS '业务流水号';
COMMENT ON COLUMN TB_IBPS_FREE_MESSAGE.MSG_DIRECTION IS 'IN-来账, OUT-往账';
COMMENT ON COLUMN TB_IBPS_FREE_MESSAGE.SEND_STATUS IS 'PENDING-待发送, SENT-已发送, FAILED-发送失败';
COMMENT ON COLUMN TB_IBPS_FREE_MESSAGE.CROSS_BORDER_TYPE IS '跨境通类型';
COMMENT ON COLUMN TB_IBPS_FREE_MESSAGE.CROSS_BORDER_ORIG_SERIAL IS '跨境通原业务流水号';

-- 3. Data Import Records
CREATE TABLE TB_IBPS_IMPORT_RECORD (
    ID              NUMBER(20) PRIMARY KEY,
    FILE_NAME       VARCHAR2(200) NOT NULL,
    FILE_TYPE       VARCHAR2(20) NOT NULL,
    TARGET_TABLE    VARCHAR2(50) NOT NULL,
    TOTAL_ROWS      NUMBER(10),
    SUCCESS_ROWS    NUMBER(10),
    FAIL_ROWS       NUMBER(10),
    STATUS          VARCHAR2(20),
    ERROR_MSG       CLOB,
    WS_SESSION_ID   VARCHAR2(100),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE
);

COMMENT ON TABLE TB_IBPS_IMPORT_RECORD IS '数据导入记录表';
COMMENT ON COLUMN TB_IBPS_IMPORT_RECORD.FILE_TYPE IS 'IBPSODT0301/IBPSODT0305/IBPSODT0401/IBPSODT0402/IBPSODT0601/IBPSODT0991';
COMMENT ON COLUMN TB_IBPS_IMPORT_RECORD.STATUS IS 'PARSING-解析中, INSERTING-入库中, DONE-完成, FAILED-失败';

-- 4. IBPS Parameter (IBPSODT0301)
CREATE TABLE TB_IBPS_PARAM (
    ID              NUMBER(20) PRIMARY KEY,
    PARAM_CODE      VARCHAR2(50) NOT NULL,
    PARAM_NAME      VARCHAR2(200),
    PARAM_VALUE     VARCHAR2(500),
    EFFECTIVE_DATE  TIMESTAMP(3),
    EXPIRY_DATE     TIMESTAMP(3),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE
);

COMMENT ON TABLE TB_IBPS_PARAM IS '公共参数表';

-- 5. IBPS Limit (IBPSODT0305)
CREATE TABLE TB_IBPS_LIMIT (
    ID              NUMBER(20) PRIMARY KEY,
    LIMIT_TYPE      VARCHAR2(50),
    LIMIT_AMOUNT    NUMBER(18,2),
    CURRENCY        VARCHAR2(10),
    EFFECTIVE_DATE  TIMESTAMP(3),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE
);

COMMENT ON TABLE TB_IBPS_LIMIT IS '金额上限表';

-- 6. Bank Type (IBPSODT0401)
CREATE TABLE TB_IBPS_BANK_TYPE (
    ID              NUMBER(20) PRIMARY KEY,
    BANK_TYPE_CODE  VARCHAR2(20) NOT NULL,
    BANK_TYPE_NAME  VARCHAR2(200),
    PARENT_CODE     VARCHAR2(20),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE
);

COMMENT ON TABLE TB_IBPS_BANK_TYPE IS '行别信息表';

-- 7. Routing (IBPSODT0402)
CREATE TABLE TB_IBPS_ROUTING (
    ID              NUMBER(20) PRIMARY KEY,
    INST_CODE       VARCHAR2(20) NOT NULL,
    ROUTE_TYPE      VARCHAR2(20),
    TARGET_INST     VARCHAR2(20),
    EFFECTIVE_DATE  TIMESTAMP(3),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE
);

COMMENT ON TABLE TB_IBPS_ROUTING IS '参与机构信息表';

-- 8. Peer Certificate (IBPSODT0601)
CREATE TABLE TB_IBPS_PEER_CERT (
    ID              NUMBER(20) PRIMARY KEY,
    INST_CODE       VARCHAR2(20) NOT NULL,
    CERT_SN         VARCHAR2(100),
    CERT_CONTENT    CLOB,
    CERT_STATUS     VARCHAR2(10),
    EFFECTIVE_DATE  TIMESTAMP(3),
    EXPIRY_DATE     TIMESTAMP(3),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE
);

COMMENT ON TABLE TB_IBPS_PEER_CERT IS '证书档案信息表';
COMMENT ON COLUMN TB_IBPS_PEER_CERT.CERT_STATUS IS 'ACTIVE-有效, REVOKED-已撤销';

-- 9. CCPC Node (IBPSODT0991)
CREATE TABLE TB_IBPS_CCPC_NODE (
    ID              NUMBER(20) PRIMARY KEY,
    NODE_CODE       VARCHAR2(20) NOT NULL,
    NODE_NAME       VARCHAR2(200),
    NODE_IP         VARCHAR2(50),
    NODE_PORT       NUMBER(6),
    STATUS          VARCHAR2(10),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE
);

COMMENT ON TABLE TB_IBPS_CCPC_NODE IS 'CCPC节点数据表';

-- 10. Local Certificate Management
CREATE TABLE TB_IBPS_LOCAL_CERT (
    ID              NUMBER(20) PRIMARY KEY,
    CHANGE_TYPE     VARCHAR2(10) NOT NULL,
    CERT_SN         VARCHAR2(100),
    CERT_CONTENT    CLOB,
    STATUS          VARCHAR2(20),
    OPERATOR        VARCHAR2(64),
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE
);

COMMENT ON TABLE TB_IBPS_LOCAL_CERT IS '本行数字证书管理表';
COMMENT ON COLUMN TB_IBPS_LOCAL_CERT.CHANGE_TYPE IS 'CC00-新增, CC02-撤销';
COMMENT ON COLUMN TB_IBPS_LOCAL_CERT.STATUS IS 'APPLIED-已申请, CONFIRMED-已确认, FAILED-失败';

-- 11. Contact Management
CREATE TABLE TB_IBPS_CONTACT (
    ID              NUMBER(20) PRIMARY KEY,
    NAME            VARCHAR2(100) NOT NULL,
    DEPT            VARCHAR2(200),
    OFFICE_PHONE    VARCHAR2(30),
    MOBILE          VARCHAR2(20),
    PBOC_KEY_CARD   VARCHAR2(50),
    BIZ_TYPES       VARCHAR2(500),
    DEL_FLAG        NUMBER(1) DEFAULT 0,
    CREATE_TIME     TIMESTAMP(3) DEFAULT SYSDATE,
    UPDATE_TIME     TIMESTAMP(3)
);

COMMENT ON TABLE TB_IBPS_CONTACT IS '行内联系人信息表';
COMMENT ON COLUMN TB_IBPS_CONTACT.BIZ_TYPES IS '业务类型(逗号分隔)';
COMMENT ON COLUMN TB_IBPS_CONTACT.DEL_FLAG IS '0-正常, 1-已删除';

-- 12. Transaction Trace Log (Core)
CREATE TABLE TRX_BUSI_TRACE_LOG (
    KEY_ID          VARCHAR2(20) NOT NULL,
    BUSI_SERIAL     VARCHAR2(64) NOT NULL,
    TRANS_CODE      VARCHAR2(8),
    STEP            VARCHAR2(50),
    EVENT_DATETIME  TIMESTAMP(3),
    CREATE_DATETIME DATE,
    CONSTRAINT PK_TRX_BUSI_TRACE_LOG PRIMARY KEY (KEY_ID)
);

COMMENT ON TABLE TRX_BUSI_TRACE_LOG IS '交易轨迹流水表';
COMMENT ON COLUMN TRX_BUSI_TRACE_LOG.TRANS_CODE IS 'FCRS0001/FCRR0001/FDRS0001/FDRR0001/FTCRPR01/FTCRPE01/FCBS0001/FCBR0001';
COMMENT ON COLUMN TRX_BUSI_TRACE_LOG.STEP IS '步点代码: RECV_*/CHECK_*/ACCT_*/SEND_*/ROLLBACK_*';

-- Indexes for trace queries
CREATE INDEX IDX_IBPS_TRACE_SERIAL ON TRX_BUSI_TRACE_LOG(BUSI_SERIAL);
CREATE INDEX IDX_IBPS_TRACE_TRANS_CODE ON TRX_BUSI_TRACE_LOG(TRANS_CODE);
CREATE INDEX IDX_IBPS_TRACE_EVENT_TIME ON TRX_BUSI_TRACE_LOG(EVENT_DATETIME);
